# /.github/workflows/deploy-api-lambda.yml (Using esbuild)
name: Deploy API Lambda to AWS (OIDC)
on:
  push:
    branches: [main]
    paths: ['api-lambda/**', '.github/workflows/deploy-api-lambda.yml']
  workflow_dispatch:
jobs:
  deploy:
    name: Build and Deploy API Lambda
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
        run:
          working-directory: ./api-lambda # 默认工作目录
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: api-lambda/package-lock.json # 注意路径

      - name: Install Dependencies
        run: npm ci # 在 api-lambda 目录运行

      - name: Build with esbuild
        run: npm run build # 在 api-lambda 目录运行

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::015590450538:role/My_LambdaImageProcessorRole_20250329
          role-session-name: GitHubActionsApiLambdaDeploy-${{ github.run_id }}
          aws-region: us-west-2
        # 不需要设置 working-directory

      - name: Create deployment package
        run: |
          echo "Zipping contents of api-lambda/dist..."
          cd api-lambda/dist && zip -r ../../api-lambda-deployment.zip .
        working-directory: ./ # 运行在仓库根目录

      - name: Deploy to AWS Lambda
        run: |
          echo "Deploying api-lambda function code..."
          aws lambda update-function-code \
            --function-name images_getImagesApi_20250329 \
            --zip-file fileb://api-lambda-deployment.zip \ # zip 包在根目录
            --region us-west-2 \
            --publish
        working-directory: ./ # 运行在仓库根目录
