name: Deploy Sync Lambda to AWS (OIDC)

on:
  push:
    branches:
      - main
    paths:
      - 'sync-lambda/**'
      - '.github/workflows/deploy-sync-lambda.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy Sync Lambda
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
        run:
          working-directory: ./sync-lambda
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: sync-lambda/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Build with esbuild
        run: npm run build

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::015590450538:role/My_LambdaImageProcessorRole_20250329
          role-session-name: GitHubActionsSyncLambdaDeploy-${{ github.run_id }}
          aws-region: us-west-2

      - name: Create deployment package
        run: |
          echo "Zipping contents of sync-lambda/dist..."
          cd dist && zip -r ../../sync-lambda-deployment.zip .
        working-directory: ./sync-lambda # Ensure zip happens relative to this dir

      - name: Deploy to AWS Lambda
        run: |
          echo "Deploying sync-lambda function code..."
          aws lambda update-function-code \
            --function-name images_20250329 \
            --zip-file fileb://sync-lambda-deployment.zip \
            --region us-west-2 \
            --publish
        working-directory: ./ # Run AWS CLI from repo root where zip file is
