# /.github/workflows/deploy-sync-lambda.yml (Using esbuild)
name: Deploy Sync Lambda to AWS (OIDC)
on:
  push:
    branches: [main]
    paths: ['sync-lambda/**', '.github/workflows/deploy-sync-lambda.yml']
  workflow_dispatch:
jobs:
  deploy:
    name: Build and Deploy Sync Lambda
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults: # 设置默认工作目录
        run:
          working-directory: ./sync-lambda
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # 添加 npm 缓存
          cache-dependency-path: sync-lambda/package-lock.json # 缓存路径

      - name: Install Dependencies
        run: npm ci # 在 sync-lambda 目录下运行

      - name: Build with esbuild # 新增 Build 步骤
        run: npm run build # 运行 package.json 中的 build 命令

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::015590450538:role/My_LambdaImageProcessorRole_20250329
          role-session-name: GitHubActionsSyncLambdaDeploy-${{ github.run_id }}
          aws-region: us-west-2

      - name: Create deployment package # 修改打包步骤
        run: |
          echo "Creating deployment package from dist..."
          # 进入构建输出目录并打包其内容
          cd dist
          zip -r ../../sync-lambda-deployment.zip .
        working-directory: ./sync-lambda # 确保此命令也在 sync-lambda 目录运行（或调整路径）
        # 修正: 上面的 zip 命令路径不对，应该在根目录操作 zip
      - name: Create deployment package (Corrected)
        run: |
          echo "Zipping contents of sync-lambda/dist..."
          # 在仓库根目录操作，打包 sync-lambda/dist 下的内容
          zip -j sync-lambda-deployment.zip sync-lambda/dist/*
        working-directory: ./ # 运行在仓库根目录

      - name: Deploy to AWS Lambda
        run: |
          echo "Deploying sync-lambda function code..."
          aws lambda update-function-code \
            --function-name images_20250329 \
            --zip-file fileb://sync-lambda-deployment.zip \ # zip 包现在在根目录
            --region us-west-2 \
            --publish
        working-directory: ./ # 确保在根目录运行
